version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
      - image: redis
    steps:
      - checkout
      - run: npm install
      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
